version: '2'
services:
  server:
    environment:
      - 'NODE_ENV=production'
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=3000'
    image: 'fanney13/tictactoe:${GIT_COMMIT}'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres' #Server er háður því að postgres sé uppi og keyrandi
    links:
      - 'postgres'
  postgres:
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    image: postgres
    ports:
     - "5432:5432"

#Segir okkur að þetta keyrist á productionmode, hostinn er postgres. 
