version: '2'
services:
  server:
    environment:
      - 'NODE_ENV=production'
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=3000'
    image: 'fanney13/tictactoe:${GIT_COMMIT}'
    ports:
      - '80:3000'
    depends_on:
      - 'postgres' #Server depends on postgres to be up and running
    links:
      - 'postgres'
  postgres:
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    image: postgres
    ports:
     - "5432:5432"

#Tells you it runs in produtionmode.
